/*
    sql file generated by 'python manage.py sqlmigrate polls 0001 >> ./polls/migration/migrations.sql
        note this will generate based on the database you set in settings.py!
        does NOT run the sql file!
        great for checking what Django will do
            alternatively, you can use python manage.py check to check any problems with your project

    Primary keys are automatically generated by default (you can turn this off)
    Foreign keys will have "_id" appended

    ! Running migrate multiple times will update your database schema (if any changes made).
        greatly improves development and data modeling efficiency since you dont have to drop tables manually!
*/

BEGIN;
--
-- Create model Question
--
CREATE TABLE "polls_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question_test" varchar(50) NOT NULL, "pub_date" datetime NOT NULL);
--
-- Create model Choice
--
CREATE TABLE "polls_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "choice_text" varchar(200) NOT NULL, "votes" integer NOT NULL, "question_id" bigint NOT NULL REFERENCES "polls_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "polls_choice_question_id_c5b4b260" ON "polls_choice" ("question_id");
COMMIT;
